### ISSUE TITLE
Calculate tax documentation differs from the REST API docs

### ISSUE THREAD

**Issue by prwhitehead** [taxamo/taxamo-php#10]
Hello. 

The REST API specifies that the Calculate Tax requires the public token, but the documentation for Taxamo PHP doesn't specify any token is required in the body of the request. The error messages returned is only ever the same obfuscated exception `TaxamoValidationException`.
```
Validation error for https://api.taxamo.com/api/v1/tax/calculate
```

The issue is that in the PHP docs the following is specified: 
```
$resp = $taxamo->calculateTax(array('transaction' => $transaction));
```
Where as the following is actually required by the REST API: 
```
$resp = $taxamo->calculateTax(array(
   'transaction' => $transaction, 
   'public_key'  => 'KEY'
));
```
Another issue was that the REST API seems to require the customer_id to be a string, but as the PHP API and because of the obfuscated exception it was not immediately what the issue was. 

Thanks, I hope this is helpful.

**Comment by nevenavv** [comment]
Instructions for using the lib are at http://www.taxamo.com/doc/api/php/
As stated there, upon initialization you should provide token:
```$taxamo = new Taxamo(new APIClient('your_private_key', 'https://api.taxamo.com'));```
 And that will be used (added as header param) for all the calls.
[Documentation](http://www.taxamo.com/apidocs/api/v1/tax/docs.html#POSTcalculate) also states that for calculate tax you can provide either private or public token, so you could initialize it here with public token, but you won't be able to make calls to methods that require private token, so you probably should use private.
Have you inspect other data from [TaxamoValidationException](https://github.com/taxamo/taxamo-php/blob/b1ec22b9b0bee0eb7274a2a217dcb3655ea7bf49/lib/Taxamo/Swagger.php#L291)?

**Comment by prwhitehead** [comment]
`Instructions for using the lib` are wrong: http://www.taxamo.com/doc/api/php/ => Pre-calculating tax

It states that this is all that is required to calculate the tax for the Lines added to the transaction: 
```
$resp = $taxamo->calculateTax(array('transaction' => $transaction));
```
This is incorrect. The public token is also required to perform this action, but because only a generic exception is returned for all errors from the API, it is much harder to debug. 

```
$resp = $taxamo->calculateTax(array('transaction' => $transaction, 'public_token' => TOKEN));
```

The issue here for created so you could update the docs and help someone else.

**Comment by nevenavv** [comment]
In paragraph before Pre-calculating tax (Setting up Taxamo API), there is that requirement to set token.

I had this working example in mind:
```
<?php

require_once('lib/Taxamo.php');

$taxamo = new Taxamo(new APIClient('SamplePublicTestKey1', 'https://api.taxamo.com'));

$transaction_line1 = new Input_transaction_line();
$transaction_line1->amount = 200;
$transaction_line1->custom_id = 'line1';

$transaction_line2 = new Input_transaction_line();
$transaction_line2->amount = 100;
$transaction_line2->custom_id = 'line2';
$transaction_line2->product_type = 'e-book';

$transaction = new Input_transaction();
$transaction->currency_code = 'USD';
$transaction->buyer_ip = '127.0.0.1';
$transaction->billing_country_code = 'IE';
$transaction->force_country_code = 'FR';
$transaction->transaction_lines = array($transaction_line1, $transaction_line2);

try {
  $resp = $taxamo->calculateTax(array('transaction' => $transaction));
} catch (TaxamoAuthenticationException $ae) {
  echo 'Caught exception: ',  $ae->getMessage(), "<br/>";
  echo 'Post data: ',  $ae->post_data, "<br/>";
  echo 'Response: ',  $ae->response, "<br/>";
} catch (TaxamoValidationException $ve) {
  echo 'Caught exception: ',  $ve->getMessage(), "<br/>";
  echo 'Errors: <pre>',  print_r($ve->errors), "</pre><br/>";
  echo 'Validation failures: <pre>',  print_r($ve->validation_failures), "</pre><br/>";
  echo 'Post data: ',  $ve->post_data, "<br/>";
  echo 'Response: ',  $ve->response, "<br/>";
}

echo "Total amount: ".$resp->transaction->total_amount;
?>
```
If you omit to provide correct token, something similar to this will be displayed:
```
Caught exception: Unauthorized API request to https://api.taxamo.com/api/v1/tax/calculate: {"errors":["Please provide correct public token."]}
Post data: {"transaction":{"force_country_code":"FR","buyer_ip":"127.0.0.1","billing_country_code":"IE","currency_code":"USD","transaction_lines":[{"custom_id":"line1","amount":200},{"custom_id":"line2","product_type":"e-book","amount":100}]}}
Response: {"errors":["Please provide correct public token."]}
```
And regarding TaxamoValidationException, you can try and omit to set transaction_lines. Then, we'll have something like this:
```
Caught exception: Validation error for https://api.taxamo.com/api/v1/tax/calculate
Errors:
Array
(
    [0] => Validation failed: 
    [1] => {:transaction {:transaction_lines missing-required-key}}
)
1

Validation failures:
stdClass Object
(
    [transaction] => stdClass Object
        (
            [transaction_lines] => missing-required-key
        )

)
1

Post data: {"transaction":{"force_country_code":"FR","buyer_ip":"127.0.0.1","billing_country_code":"IE","currency_code":"USD"}}
Response: {"errors":["Validation failed: ","{:transaction {:transaction_lines missing-required-key}}"],"nickname":"calculateTax","validation_failures":{"transaction":{"transaction_lines":"missing-required-key"}}}
```

Hope this helps.

**Comment by prwhitehead** [comment]
Hello. 

Thank you for this; the issue would obviously then be that because the PHP documentation specifies use of the Private Token and never mentions using another token for some of the endpoints that it should be updated to avoid this in the future. Thats the issue, the code works fine with the right token, but the documentation needs updating.

**Comment by nevenavv** [comment]
Hi.

So to wrap this up:
Setting private token here:
```$taxamo = new Taxamo(new APIClient('SamplePrivateTestKey1', 'https://api.taxamo.com'));```
Is actually right way to go, as it will ensure there is no authentication problem for all methods, whether they require private or public token (every method where public token is sufficient will also work with private token, and that's stated in documentation, as it is the case with calculateTax method). Setting public token here is ok only if you'll only call methods where public token is sufficient (probably not real case scenario). Documentation is obviously not specific on that point, so could be updated. Thanks for reporting.

**Comment by prwhitehead** [comment]
But the docs are still wrong. I'm not sure why adding a line in the documentation regarding adding the 'public_token' to the body of the request is such a big deal? Surely adding those couple of lines would save someone else from spending an hour comparing REST and PHP documentation?

**Comment by nevenavv** [comment]
There is no need to add 'public_token' to the body of the request. It's enough to set token upon initialization of Taxamo as stated above. Do you have some example where that's not working? Validation error you mentioned in first post is not an issue with wrong token.

**Comment by tlipski** [comment]
OK, so to clarify (I will update the docs in a minute):

You can calculate tax using either private token or public token. 

The only difference here is that when using private_token for tax calculation, you can override the `buyer_ip` country field, as it is assumed that  the call is being made server-side. As some API calls work with private tokens only, it is more feasible to use private token and supply the buyer_ip. 

I will appropriate commentary to the docs.

**Comment by tlipski** [comment]
ok, please check http://www.taxamo.com/doc/api/php/

**Comment by tlipski** [comment]
Also Paul - thank you for your input - it's always good to have this kind of feedback from our users :)

**Comment by prwhitehead** [comment]
Thanks for the addition. I just wanted to save some one else the time i spent figuring out the error in the docs. Could I be bold enough to suggest an additional code example using the public token in place of the private token. As a developer that learns mostly from example, the code samples are very important to understanding how the code fits together. 

Thanks for the help. :)

**Comment by tlipski** [comment]
Hmm, the public token is destined to be used JavaScript-side mostly - with RESTful API it is better to use private token. 

You need to use private token to propagate buyer_ip or confirm a transaction, so using public token there might lead to some confusion.
