### ISSUE TITLE
Auto Loader not working with PHP examples on taxamo.com samples

### ISSUE THREAD

**Issue by danieliser** [taxamo/taxamo-php#2]
Specifically it uses Input_transaction, but the auto loader function does not change case, and the file under models is stored as input_transaction.

Using new input_transaction works but that the class defined there is Input_transaction. So either the file names need to be changed to match, or the loader needs to make class names lower case during file lookup. Either way it needs to be standardized as some files are named getDailySettlementStatsOut with a class GetDailySettlementStatsOut.

This will cause naming issues on different versions of PHP.

I worked around it by simply using the lowercase. Maybe just update the samples in the API is a simpler fix.

**Comment by danieliser** [comment]
Seems to still be a problem in latest build. Worked fine on test servers(windows) but got this on live server(ubuntu).

Fatal error: Class 'input_transaction' not found in /srv/users/serverpilot/apps/danieliser/public/wp-content/plugins/rcp-taxamo/includes/class-rcp-taxamo-payments.php on line 60

It seems to be to due with this line.

https://github.com/taxamo/taxamo-php/blob/master/lib/Taxamo/Swagger.php#L15

Currently your file structure has folders name models and data, your script is looking for Models though.

Likely just oversight but on linux servers file naming is case sensitive.

Patched by simply renaming folder to Models, or those lines to models. Either way they need to match exactly, same for Class names and file names really.

**Comment by tlipski** [comment]
Yeah, git played a trick on me by lowercasing the Models dir, whereas Taxamo stayed uppercase. My initial test copied the original repository from my computer to Ubuntu server (where Models was uppercase), so I didn't notice that.

Anyway, I have updated Swagger.php to look for models/ instead of Models/ and released version 1.0.12.
