### ISSUE TITLE
Exceptions should use an standard output to let programmers handle them

### ISSUE THREAD

**Issue by PapayaMedia** [taxamo/taxamo-php#3]
I'm developing an integration of Taxamo API using this library.

When creating a transaction, if Taxamo API returns an error code (40x), Swagger throws an exception in a different format for each http code, so I can't program a way to know the error, because I don't even know it was a 400, 401 or 404 error because this information is not included in the Exception message.

I'm talking about Swagger.php file, lines 105 to 123.

**Comment by PapayaMedia** [comment]
Thank you for this modification... now, based on the exception type, I am able to program a better way to deal with the errors.

**Comment by tlipski** [comment]
ok, so I assume that this solves this issue.
