### ISSUE TITLE
Taxamo PHP version

### ISSUE THREAD

**Issue by PapayaMedia** [taxamo/taxamo-php#4]
Is it possible to add the Taxamo PHP library version anywhere in the files? Maybe a VERSION.txt file, or just a "Version" line at the top of Taxamo.php file... or maybe a method in the class ($taxamo->getVersion()).

It is to be able to check for the version of the Library to be sure a minimum version is installed.

I'm developing a Drupal module so I can't control what the website administrators install in their websites and this would be very helpful.

Thank you.

**Comment by tlipski** [comment]
Definitely, I will add it on occasion

**Comment by tlipski** [comment]
just released 1.0.13, and library version is set in Taxamo::$VERSION static public field.

**Comment by PapayaMedia** [comment]
The last commit is from 1 month ago, so this is not included.

**Comment by tlipski** [comment]
ah, my bad - it should be visible now
