### ISSUE TITLE
How to use createSMSToken()?

### ISSUE THREAD

**Issue by PapayaMedia** [taxamo/taxamo-php#5]
May you guide me on how to use the method createSMSToken()?

The param it is expecting is $body and I don't know what to send there... I'd be expecting to send something different, like $taxamo->createSMSToken($country_code, $recipient);

**Comment by tlipski** [comment]
The convention here is to use input object: [CreateSmsTokenIn](https://github.com/taxamo/taxamo-php/blob/master/lib/Taxamo/models/createSMSTokenIn.php), and this object has necessary fields.

**Comment by PapayaMedia** [comment]
It perfectly worked... thank you.
