### ISSUE TITLE
Attribute missing in Validate VAT number

### ISSUE THREAD

**Issue by PapayaMedia** [taxamo/taxamo-php#6]
Hello... it looks that Taxamo API has been modified for the method Validate VAT number. There is a new attribute added to the output named "buyer_tax_number_valid" (http://www.taxamo.com/apidocs/api/v1/tax/docs.html#GETvat_numberstax-numbervalidate)

Can you include it in the php object response?

**Comment by PapayaMedia** [comment]
I can only attach images... so... here is the diff to add it:
https://www.dropbox.com/s/u8h4kjnhdar68jc/Captura%20de%20pantalla%202015-02-03%2010.08.07.png?dl=0

**Comment by tlipski** [comment]
yes, that was released on the weekend and I will update API libs shortly

**Comment by tlipski** [comment]
just released 1.0.13, with the new fields being added to the PHP api

**Comment by PapayaMedia** [comment]
The last commit is from 1 month ago, so this is not included.

**Comment by tlipski** [comment]
ah, my bad - it should be visible now
