### ISSUE TITLE
Taxamo class not loaded

### ISSUE THREAD

**Issue by prwhitehead** [taxamo/taxamo-php#8]
Hey, Ive been trying all kinds of things to get the Taxamo PHP suite up and running in a large Symfony app. It doesn't seem to be being loaded, the `APIClient` however is. 
```  
ClassLoader {
  -prefixLengthsPsr4: array:6 
  -prefixDirsPsr4: array:23 
  -fallbackDirsPsr4: []
  -prefixesPsr0: array:21
  -fallbackDirsPsr0: array:1 
  -useIncludePath: false
  -classMap:
    "APIClient" => "<site-path>/vendor/taxamo/taxamo-php/lib/Taxamo/Swagger.php"
    "Additional_currencies" => "<site-path>/vendor/taxamo/taxamo-php/lib/Taxamo/models/additional_currencies.php"
    ...
    "Taxamo" => false
  ]
  -classMapAuthoritative: false
}
```

There is no namespace registered for the suite so when the `APIClient` was called it was from the global namespace. 

The entry added to my composer.json file was `"taxamo/taxamo-php": "1.*"`, so I am a little lost as to why it was not loaded from the suits class map.

**Comment by tlipski** [comment]
Thanks for the report, I will look into it.

**Comment by prwhitehead** [comment]
Hey, thanks. If it helps, I have created a brand new test project too and tried to the load the class that way too. This is from dumping the loader: https://gist.github.com/prwhitehead/354cfa0553361bde6e3c

**Comment by tlipski** [comment]
ok, got it, "lib/Taxamo.php" was missing from autoload declaration. Will release new version soon

**Comment by tlipski** [comment]
ah, great, see https://status.github.com/

10:00 UTC We continue to respond to an ongoing DDoS attack. Some users may experience intermittent connectivity with git operations as we mitigate the problem.

**Comment by tlipski** [comment]
OK, 1.0.20 released - please verify if it helped

**Comment by prwhitehead** [comment]
This works perfectly, thank you.

**Comment by tlipski** [comment]
No problem at all, sorry for the inconvenience.

**Comment by prwhitehead** [comment]
Its great that you were able to get to it so quickly, thanks for the time you are putting in :)
