### ISSUE TITLE
Vat Validation timeout

### ISSUE THREAD

**Issue by prwhitehead** [taxamo/taxamo-php#9]
Hello. I have been using the PHP Library. I think there is an issue in the `Taxamo::validateTaxNumber()` method. It seems that they require a header key to be set `Private-Token`. 

I have a working example using Guzzle: 
```
        #Validate a vat number
        $client = new Guzzle([
            'base_url' => [
                'https://api.taxamo.com/api/{version}/tax/vat_numbers/{vat_number}/validate', [
                    'version' => 'v1',
                    'vat_number' => $vatNumber,
                ]
            ],
            'defaults' => [
                'headers' => ['Private-Token' => $taxamoPrivateKey],
                'query'   => ['country_code' => $countryCode],
            ]
        ]);

        $response = $client->get();
        $body = json_decode($response->getBody()->getContents());
```

However using the Taxamo library: 
```
        $taxamoApiUrl = 'https://api.taxamo.com';
        $taxamo = new Taxamo(new APIClient($taxamoPublicKey, $taxamoApiUrl));
        dump($taxamo->validateTaxNumber($countryCode, $vatNumber)); die;
```
I get the following:
TIMEOUT: api call to https://api.taxamo.com/api/v1/tax/vat_numbers/12345678/validate?country_code=GB took more than 5s to return. 

I am using dev-master `"taxamo/taxamo-php": "1.*",` and including the Taxamo.php file manually in my app_dev.php (because of the reasons stated in the other open issue). 

Thanks in advance. :)

**Comment by tlipski** [comment]
Hmm, this is weird, since this message should not be present in most recent (1.0.17) version. Anyway, this raises a good point - VAT number validation can take more than 5s, so I will increase the limit.

**Comment by tlipski** [comment]
OK, 1.0.20 released - please verify if it helped

**Comment by prwhitehead** [comment]
Hello. 

This allows an error message to be displayed: 

```
Unauthorized API request to https://api.taxamo.com/api/v1/tax/vat_numbers/123454567/validate?country_code=GB: {"errors":["Please provide correct private token."]}
```

The working example I have with Guzzle and also the docs require a header to be set `Private-Token`, which the `validateTaxNumber` does not set as far as I can see?

**Comment by tlipski** [comment]
ok, that's more informative - are you using your private or public token?  The server-side calls should be made with private token.

**Comment by prwhitehead** [comment]
Hey, 

Im using the private token and making the request server side.

This code using Guzzle works: 

```
        // Validate a vat number
        $client = new Guzzle([
            'base_url' => [
                'https://api.taxamo.com/api/{version}/tax/vat_numbers/{vat_number}/validate', [
                    'version' => 'v1',
                    'vat_number' => $vatNumber,
                ],
            ],
            'defaults' => [
                'headers' => ['Private-Token' => $this->taxamoPrivateKey],
                'query'   => ['country_code' => $countryCode],
            ],
        ]);

        $response = $client->get();
        $body = json_decode($response->getBody()->getContents());
```

As you can see the header is set for the private key. 

As far as I can see the `validateTaxNumber` which I am trying to use is not setting this header. 

```
  public function validateTaxNumber($country_code=null, $tax_number) {

  		//parse inputs
  		$resourcePath = "/api/v1/tax/vat_numbers/{tax_number}/validate";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();
      $headerParams['Accept'] = 'application/json';
      $headerParams['Content-Type'] = 'application/json';

      if($country_code != null) {
  		  $queryParams['country_code'] = $this->apiClient->toQueryValue($country_code);
  		}
  		if($tax_number != null) {
  			$resourcePath = str_replace("{" . "tax_number" . "}",
  			                            $this->apiClient->toPathValue($tax_number), $resourcePath);
  		}
  		//make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'validateTaxNumberOut');
  		return $responseObject;

      }
```

However, by adding the following to the method: 
```
$headerParams['Private-Token'] = 'priv_test_<rest of number>';
```
The response comes back straight away as I would have expected. I think the reason for the 5 second time out is that the header wasn't set. 

The REST docs state that the following is required (http://www.taxamo.com/apidocs/ under Authenticating calls): 
```
curl -H "Private-Token: SamplePrivateTestKey1" https://api.taxamo.com/api/v1/tax/vat_numbers/6388047V/validate?country_code=IE
```

**Comment by tlipski** [comment]
The token is set in https://github.com/taxamo/taxamo-php/blob/master/lib/Taxamo/Swagger.php#L75 - are you sure you are providing it correctly when instantating APIClient ? Can you try with SamplePrivateTestKey1?

**Comment by prwhitehead** [comment]
Hey, you were right, it was an issue with the wrong key being passed, sorry for bothering you with that. Thanks again for making the fixes so quickly. 

Have a nice weekend.

**Comment by tlipski** [comment]
Ah, no problem at all. If you run into any issues or have any questions feel free to contact us - at least we can make that part of VAT as painless as possible ;)
